-- Insert sample recipes
INSERT INTO recipes (name, description, meal_type, ingredients, instructions, health_benefits, image_url, biomarker_tags, calories, prep_time, cook_time, servings, is_public) VALUES
('Tart Cherry Parfait', 'Nutritious tart cherries over mild coconut yogurt', 'breakfast', '["1 cup coconut yogurt", "1/2 cup tart cherries", "2 tbsp granola", "1 tbsp honey"]'::jsonb, 'Layer coconut yogurt with tart cherries and granola. Drizzle with honey.', '["increase melatonin", "omega 3 brain fuel"]'::jsonb, 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500', '["sleep", "brain health"]'::jsonb, 220, 5, 0, 1, true),
('Banana Crepes', 'Delicious crepes with fresh banana slices', 'breakfast', '["2 eggs", "1 cup flour", "1 cup milk", "2 bananas", "maple syrup"]'::jsonb, 'Mix batter and cook thin crepes. Top with sliced bananas and syrup.', '["reduce blood pressure"]'::jsonb, 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=500', '["heart health"]'::jsonb, 350, 10, 15, 2, true),
('Spinach Quiche', 'Protein-rich quiche with fresh spinach', 'breakfast', '["6 eggs", "2 cups spinach", "1 cup cheese", "1 pie crust", "1/2 cup milk"]'::jsonb, 'Mix ingredients and bake at 375F for 45 minutes.', '["high protein", "iron rich"]'::jsonb, 'https://images.unsplash.com/photo-1611171711912-e72fe4be5752?w=500', '["energy", "immunity"]'::jsonb, 280, 15, 45, 6, true),
('Coconut Curry Ramen', 'Warming coconut curry broth with noodles', 'lunch', '["ramen noodles", "coconut milk", "curry paste", "vegetables", "tofu"]'::jsonb, 'Cook noodles. Simmer coconut milk with curry paste. Combine and top with vegetables.', '["anti-inflammatory", "digestive support"]'::jsonb, 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=500', '["gut health", "immunity"]'::jsonb, 420, 10, 20, 2, true),
('Grilled Veggie Wraps', 'Fresh vegetables grilled and wrapped', 'lunch', '["tortillas", "bell peppers", "zucchini", "hummus", "spinach"]'::jsonb, 'Grill vegetables. Spread hummus on tortilla and add grilled veggies and spinach.', '["high fiber", "antioxidants"]'::jsonb, 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=500', '["digestive health", "skin health"]'::jsonb, 310, 15, 10, 2, true),
('Roasted Duck', 'Perfectly roasted duck with herbs', 'dinner', '["1 whole duck", "herbs", "garlic", "potatoes", "carrots"]'::jsonb, 'Season duck and roast at 400F for 2 hours. Serve with roasted vegetables.', '["high protein", "B vitamins"]'::jsonb, 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500', '["muscle building", "energy"]'::jsonb, 550, 20, 120, 4, true),
('Curry Wings', 'Spicy curry chicken wings', 'dinner', '["chicken wings", "curry powder", "yogurt", "garlic", "lime"]'::jsonb, 'Marinate wings in curry yogurt mixture. Bake at 425F for 40 minutes.', '["protein rich", "metabolism boost"]'::jsonb, 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=500', '["energy", "muscle"]'::jsonb, 380, 15, 40, 3, true);

-- Insert sample herbs
INSERT INTO herbs (name, description, category, benefits, image_url, biomarker_tags, preparation_instructions, dosage, precautions, is_public) VALUES
('Lavender & Chamomile Tea', 'This tonic may promote restful sleep', 'Relaxation', '["improves insomnia", "relieves tension"]'::jsonb, 'https://images.unsplash.com/photo-1597318112085-5c8d35a13c23?w=500', '["sleep", "stress"]'::jsonb, 'Steep 1 tsp each of dried lavender and chamomile in hot water for 5-7 minutes.', '1-2 cups before bedtime', 'Consult doctor if pregnant', true),
('Red Raspberry Tea', 'Traditional postpartum support tea', 'Postpartum Blends', '["strengthens uterus"]'::jsonb, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500', '["womens health", "recovery"]'::jsonb, 'Steep 1-2 tsp dried red raspberry leaf in hot water for 10 minutes.', '2-3 cups daily', 'Consult healthcare provider', true),
('Hormonal Balance', 'Supports thyroid and hormonal health', 'Postpartum Blends', '["improves thyroid function"]'::jsonb, 'https://images.unsplash.com/photo-1545143261-e2a63e11c062?w=500', '["hormones", "thyroid"]'::jsonb, 'Blend of vitex, maca, and rose. Steep for 8-10 minutes.', '1-2 cups daily', 'Not for use during pregnancy', true),
('Ginger & Turmeric Tonic', 'Powerful anti-inflammatory blend', 'Immune System Boosts', '["reduces inflammation", "boosts immunity"]'::jsonb, 'https://images.unsplash.com/photo-1608181831042-abd9e11c3f7e?w=500', '["immunity", "inflammation"]'::jsonb, 'Grate fresh ginger and turmeric into hot water. Add lemon and honey.', '1-2 cups daily', 'May interact with blood thinners', true),
('Echinacea & Goldenseal Blend', 'Traditional immune support', 'Immune System Boosts', '["fights infection", "immune support"]'::jsonb, 'https://images.unsplash.com/photo-1564485377539-4af72d1f6a2f?w=500', '["immunity", "cold prevention"]'::jsonb, 'Steep equal parts echinacea and goldenseal for 10 minutes.', '1 cup 2-3 times daily when ill', 'Not for long-term use', true),
('Aloe Vera Tonic', 'Gentle digestive cleanse', 'Detox Tonics', '["digestive support", "detoxification"]'::jsonb, 'https://images.unsplash.com/photo-1599591417167-8cc0a2e86f2b?w=500', '["digestion", "detox"]'::jsonb, 'Mix 2 tbsp pure aloe vera juice with water and lime.', '1/4 cup daily', 'May have laxative effect', true),
('Parasite Detox', 'Herbal antiparasitic blend', 'Detox Tonics', '["antiparasitic", "cleansing"]'::jsonb, 'https://images.unsplash.com/photo-1582385305050-c3c3b76b4b74?w=500', '["cleansing", "gut health"]'::jsonb, 'Blend of wormwood, black walnut, and clove. Steep for 15 minutes.', 'Follow practitioner guidance', 'Consult herbalist before use', true);
