name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Enable corepack / pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        working-directory: health-recommendation-app
        run: pnpm install --prefer-offline

      - name: Build
        working-directory: health-recommendation-app
        run: |
          # set GH_PAGES to true so vite.base uses /geneproof/
          GH_PAGES=true pnpm build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./health-recommendation-app/dist
          publish_branch: gh-pages
